[package]
name = "pugio"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1"
clap = { version = "4.5", features = ["derive"] }
colorgrad = { version = "0.8", features = ["preset"], default-features = false }
humansize = "2.1"
open = "5"
petgraph = { version = "0.8", features = [
    "std",
    "stable_graph",
], default-features = false }
serde_json = "1.0"
strum = { version = "0.27", features = ["derive"] }
